### ISSUE TITLE
Relative paths to NCBI and user genomes

### ISSUE THREAD

**Issue by donovan-h-parks** [Ecogenomics/GTDBNCBI#1]
In order to setup a completely independent development environment it would be helpful it the paths to NCBI and user genomes stored in the database were not absolute paths. The root directory of the genomes should be read from Config.py and appended to a relative path stored in the database.

**Comment by pchaumeil** [comment]
This has been implemented in the released version of GTDBNCBI:
commit: aa22b26e68a8853da3c661180f15ae40c36ddf3b
