### ISSUE TITLE
File file indicating path to all GTDB genomes

### ISSUE THREAD

**Issue by donovan-h-parks** [Ecogenomics/GTDBNCBI#24]
It would be nice to have an export function (perhaps in the 'metadata' menu) that allowed a flat file to be dumped indicating the absolute path to all genome directories currently in the GTDB. It is a bit non-trivial to get this at the moment given that genomes are stored in both user directories, RefSeq directories, and Genbank directories. This file would be useful for a number of downstream applications that need a way to access the genomic data of all genomes in the GTDB at a specific point in time.

**Comment by pchaumeil** [comment]
This has been implemented and will be released in the next GTDB version

**Comment by donovan-h-parks** [comment]
What menu did you put this under? It could probably go under the "power" menu as it isn't going to be of interest outside of developers.

**Comment by pchaumeil** [comment]
For the moment, The command is under metadata export:

gtdb metadata export --path --output /tmp/path_to_del.txt

It can be moved if required.

On 5/04/2016 11:49 PM, Donovan Parks wrote:

What menu did you put this under? It could probably go under the "power" menu as it isn't going to be of interest outside of developers.

##

**Comment by donovan-h-parks** [comment]
I do find this pretty confusing. I think it would be best if it was its own command (i.e., gtdb metadata genome_paths or gtdb power genome_paths).

**Comment by pchaumeil** [comment]
The new command ( gtdb power genome_paths) has been implemented and will be released in the next GTDB version
