### ISSUE TITLE
Delete genomes using genome list IDs

### ISSUE THREAD

**Issue by donovan-h-parks** [Ecogenomics/GTDBNCBI#25]
Currently, genomes can only be deleted by specifying genome IDs. It would be convenient if they could also be removed by specifying one or more genome list IDs, e.g.:

`>gtdb genomes delete --list_ids 217,218`

Most people have their genomes organized in genome lists and will wont to remove the entire list.

**Comment by pchaumeil** [comment]
This feature has been added:

Check commit : edd1ffa17ecae23a10f0b19406536da03fdd5efe
