### ISSUE TITLE
Viewing user marker sets if not currently implemented

### ISSUE THREAD

**Issue by donovan-h-parks** [Ecogenomics/GTDBNCBI#26]
Creating marker sets is a fairly rare event and in general people will not want/need to use other users marker sets as they will be very specific to a given project. Nonetheless, it would be good to support this.

```
>gtdb marker_sets view --owner uqdparks
[2016-02-03 10:55:15] INFO: GTDB v0.0.1 (NCBI database 2015-11-27)
[2016-02-03 10:55:15] INFO: gtdb marker_sets view --owner uqdparks
Database action failed. The following error(s) were reported:
        Viewing other peoples' marker sets not yet implemented.
```

**Comment by pchaumeil** [comment]
Function has been implemented.

ix in commit :a1b660be08bd879c8a03ae88c7b56e7da2e1b307
