### ISSUE TITLE
Propagate taxonomic annotations to revised NCBI genomes

### ISSUE THREAD

**Issue by donovan-h-parks** [Ecogenomics/GTDBNCBI#31]
NCBI occasionally revises genomes. This results in an incremental update to their assembly accession number (e.g., GCA_1234567.1 to GCA_1234567.2). In such cases, it would be very useful if taxonomic annotations were automatically assigned to the revised genome (i.e., from GCA_1234567.1 to GCA_1234567.2). This should reduce the amount of work required to update the taxonomy with each new pull from NCBI.

**Comment by donovan-h-parks** [comment]
Pierre, can you confirm this is now in place?

**Comment by pchaumeil** [comment]
The versioning update is in the update_database script.

However the script needs to be modified to delete all aligned markers from the previous version.

**Comment by pchaumeil** [comment]
Fixed in :
a7f9127b34385c1428c9307a8b68f7ec16e52dfe
