### ISSUE TITLE
Automatically annotate new User genomes as Bacteria or Archaea

### ISSUE THREAD

**Issue by donovan-h-parks** [Ecogenomics/GTDBNCBI#32]
It is often convienent to infer trees for just bacterial or archaeal genomes. This can be done with the taxa filter option of <code>tree create</code>. However, to ensure all genomes in a  domain are considered genomes need to be automatically annotated as being a Bacteria or Archaea. This is possible by considering the number of genes identified in the domain-specific canonical alignments and assigning genomes to the domain with the highest percentage of identified genomes. Informal testing indicates that high-quality genomes have <20% of genes in the incorrect domain marker set.

**Comment by pchaumeil** [comment]
This feature has been added.

Check commit: 8082380ac2fe4071925f6c9cb1c37817fe342df5
