### ISSUE TITLE
Automatic assignment of GTDB taxonomy for clustered genomes

### ISSUE THREAD

**Issue by donovan-h-parks** [Ecogenomics/GTDBNCBI#33]
A genome assigned to a representative should have the same GTDB taxonomy as the representative. Currently, this is enforced externally to the GTDB by updating all genomes with appropriate taxonomy strings whenever the taxonomy is updated. This works fine, except that newly added User genomes assigned to a representative will not automatically obtain a valid GTDB taxonomy until the taxonomy is updated. It would be better if such genomes were automatically given a GTDB taxonomy whenever assigned to a representative.

**Comment by pchaumeil** [comment]
This feature has been added.

Check commit: 8082380ac2fe4071925f6c9cb1c37817fe342df5
