### ISSUE TITLE
Representative genomes should never be filtered

### ISSUE THREAD

**Issue by donovan-h-parks** [Ecogenomics/GTDBNCBI#42]
The selection criteria for GTDB representatives is becoming increasingly complex. As such, some representatives actually have relatively poor CheckM quality estimates. Such genomes may represent known reduced genomes or genomes present as a single ungapped chromosome which are almost certainly complete (though may not pass the strict quality thresholds).

Selected representatives should NEVER be filtered out of the GTDB trees. These are considered trusted genomes. If the user request representatives they should always get the complete set.

**Comment by pchaumeil** [comment]
This has been has been implemented and will be available in the next release of GTDB.
