### ISSUE TITLE
Change & remove published login details

### ISSUE THREAD

**Issue by katrinleinweber** [Ecogenomics/GTDBNCBI#50]
Hello!

Did you intentionally commit:

https://github.com/Ecogenomics/GTDBNCBI/blob/8db9e1fdb7b6fca34ed6e7765c7535363b6851ac/scripts_dev/dsmz_scrape/dsmz_api_scraper.py#L52-L53

? If not, please consider [changing your BacDive password](https://bacdive.dsmz.de/api/bacdive/registration/password/change/) and factoring-out those two variables into a file that is `.gitignore`d ;-)

**Comment by pchaumeil** [comment]
Hello Katrin,

Thanks for your Email!
The DSMZ credentials have now been changed and git will ignore the dsmz_api_scraper file :) .

Cheers,
Pierre

**Comment by katrinleinweber** [comment]
You're welcome :-)
